//
//  DayChatView.swift
//  TODO
//
//  Created by John Rizkalla on 9/15/26.
//

import SwiftUI
import SwiftData
import OSLog

/// One turn of the conversation under the summary.
struct DayChatMessage: Identifiable, Equatable {
    enum Author { case user, assistant }

    let id = UUID()
    let author: Author
    var text: String
}

/// Ask about the day, under the summary that described it.
///
/// Deliberately not a separate screen: the questions people have are about the
/// paragraph they just read ("why is that the urgent one?"), and putting the
/// field anywhere else would break that thread. It talks to the same
/// `AISummaryService` for the same reason — see `AISummaryService.ask`.
struct DayChatView: View {
    @Environment(AppSettings.self) private var settings
    @Environment(\.modelContext) private var context

    /// The same service the summary above was generated by.
    @ObservedObject var service: AISummaryService
    /// Bumped by the parent when a new summary lands, which clears the thread.
    var summaryGeneration: Int

    @State private var messages: [DayChatMessage] = []
    @State private var draft = ""
    @State private var isAnswering = false
    @State private var isExpanded = false
    @FocusState private var isFieldFocused: Bool

    /// Collapsed to a single row until asked for.
    ///
    /// The summary is the point of this screen and the chat is the follow-up,
    /// so it stays out of the way until someone wants it — and a text field
    /// sitting open under a summary reads as something that must be filled in.
    private var prompt: some View {
        Button {
            withAnimation(Theme.Animation.listChange) { isExpanded = true }
            isFieldFocused = true
        } label: {
            HStack(spacing: 6) {
                Image(systemName: "bubble.and.sparkles")
                Text("Ask about your day")
                Spacer()
            }
            .font(.subheadline)
            .foregroundStyle(.white.opacity(0.85))
            .contentShape(.rect)
        }
        .buttonStyle(.plain)
    }

    private var thread: some View {
        VStack(alignment: .leading, spacing: 10) {
            ForEach(messages) { message in
                switch message.author {
                case .user:
                    HStack {
                        Spacer(minLength: 32)
                        Text(message.text)
                            .font(.subheadline)
                            .padding(.horizontal, 10)
                            .padding(.vertical, 6)
                            .background(.white.opacity(0.22), in: .rect(cornerRadius: 12))
                    }
                case .assistant:
                    Text(
                        (try? AttributedString(markdown: message.text))
                        ?? AttributedString(message.text)
                    )
                    .font(.subheadline)
                    .frame(maxWidth: .infinity, alignment: .leading)
                }
            }

            if isAnswering {
                HStack(spacing: 6) {
                    ProgressView().tint(.white).controlSize(.small)
                    Text("Thinking…").font(.caption)
                }
                .foregroundStyle(.white.opacity(0.8))
            }
        }
    }

    private var field: some View {
        HStack(spacing: 8) {
            TextField("Ask about your day", text: $draft, axis: .vertical)
                .textFieldStyle(.plain)
                .lineLimit(1...4)
                .font(.subheadline)
                .focused($isFieldFocused)
                .onSubmit(send)
                #if os(iOS)
                .submitLabel(.send)
                #endif

            Button(action: send) {
                Image(systemName: "arrow.up.circle.fill")
                    .font(.title3)
            }
            .buttonStyle(.plain)
            .disabled(!canSend)
            .opacity(canSend ? 1 : 0.4)
        }
        .padding(.horizontal, 10)
        .padding(.vertical, 7)
        .background(.white.opacity(0.18), in: .rect(cornerRadius: 12))
    }

    private var canSend: Bool {
        !draft.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty && !isAnswering
    }

    var body: some View {
        // The chat continues the summary's session, so there is nothing to
        // continue until that session exists.
        if service.canChat {
            VStack(alignment: .leading, spacing: 10) {
                if isExpanded {
                    if !messages.isEmpty || isAnswering { thread }
                    field
                } else {
                    prompt
                }
            }
            .foregroundStyle(.white)
            .tint(.white)
            .animation(Theme.Animation.listChange, value: messages)
            .animation(Theme.Animation.listChange, value: isAnswering)
            // A new summary describes a changed day, so the thread that
            // discussed the old one no longer has anything to attach to.
            .onChange(of: summaryGeneration) {
                messages = []
                draft = ""
            }
        }
    }

    private func send() {
        let question = draft.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !question.isEmpty, !isAnswering else { return }

        messages.append(.init(author: .user, text: question))
        draft = ""
        isAnswering = true

        Task { @MainActor in
            defer { isAnswering = false }
            do {
                guard let result = try await service.ask(question) else { return }
                messages.append(.init(author: .assistant, text: result.reply))

                // The chat learns the same way the summary does: someone
                // mentioning they cannot make mornings work is worth keeping
                // whichever half of the screen they said it in.
                if settings.memoryEnabled, !result.facts.isEmpty {
                    MemoryStore(context: context).remember(result.facts)
                }
            } catch {
                AppLog.data.error("Chat failed: \(error, privacy: .public)")
                messages.append(.init(
                    author: .assistant,
                    text: "Sorry — I couldn't answer that just now."
                ))
            }
        }
    }
}
